presubmits:
  - name: pull-test-dev-validate-labels-yaml
    decorate: true
    run_if_changed: 'labels.yaml'
    branches:
      - ^master$
    spec:
      containers:
        - image: gcr.io/k8s-prow/label_sync:v20201204-d90be1ef6b
          command:
            - /app/label_sync/app.binary
          args:
            - --config=labels.yaml
            - --confirm=false
            - --only=tidb-community-bots/test-dev
            - --token=/etc/github/token
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: github-token
          secret:
            secretName: github-token
  - name: pull-test-dev-rerere
    decorate: true
    always_run: true
    max_concurrency: 1
    branches:
      - ^master$
    spec:
      containers:
        - image: centos:centos7
          command: ["/bin/bash", "-c"]
          args:
            - systemctl start docker;
              docker ps;
          securityContext:
            privileged: true