presubmits:
  - name: pull-test-dev-validate-labels-yaml
    decorate: true
    run_if_changed: 'labels.yaml'
    branches:
      - ^master$
    spec:
      containers:
        - image: gcr.io/k8s-prow/label_sync:v20201204-d90be1ef6b
          command:
            - /app/label_sync/app.binary
          args:
            - --config=labels.yaml
            - --confirm=false
            - --only=tidb-community-bots/test-dev
            - --token=/etc/github/token
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: github-token
          secret:
            secretName: github-token
  - name: pull-test-dev-rerere
    decorate: true
    always_run: true
    max_concurrency: 1
    branches:
      - ^master$
    spec:
      containers:
        - name: docker-cmds
          image: docker:1.12.6
          command: [ 'docker', 'run', '-p', '80:80', 'httpd:latest' ]
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
        - name: dind-daemon
          image: docker:1.12.6-dind
          command: []
          resources:
            requests:
              cpu: 20m
              memory: 512Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      volumes:
        - name: docker-graph-storage
          flexVolume:
            driver: "ax/vol_plugin"
            fsType: "ext4"
            options:
              size_mb: "10240"
              ax_vol_type: "ax-docker-graph-storage"
